<?php

namespace App\Services;

use App\Models\ClassSubject;
use App\Models\Exam;
use App\Models\ExamSubject;
use App\Repositories\Contracts\ExamRepositoryInterface;
use App\Support\MarkParts;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * An exam's subject schedule: the per-class snapshot of the curriculum (generated by
 * ExamService) with each subject's date, times and part marks, which can be edited here.
 */
class ExamScheduleService
{
    public function __construct(private ExamRepositoryInterface $exams) {}

    public function list(Exam $exam, ?int $classId = null): Collection
    {
        return $this->exams->subjectsFor($exam, $classId);
    }

    /**
     * Edits the date, times and part marks of one subject. The part marks follow the
     * curriculum's rules (see MarkParts), checked against the subject with the input applied
     * so a partial update is still caught, and changing them once any marks exist for the
     * subject is a 409. A subject of another exam is a 404.
     *
     * @param  array<string, mixed>  $data
     */
    public function update(Exam $exam, ExamSubject $subject, array $data): ExamSubject
    {
        abort_unless($subject->exam_id === $exam->id, 404, 'Record not found.');

        return DB::transaction(function () use ($exam, $subject, $data) {
            $locked = $this->exams->lockSubject($subject);
            $applied = (clone $locked)->fill($data);

            $this->ensureTimesInOrder($applied);

            // Only when the date is being set, so an exam whose dates moved later doesn't
            // block unrelated edits to a subject that still carries an older date.
            if (array_key_exists('exam_date', $data)) {
                $this->ensureDateWithinExam($applied, $exam);
            }

            if ($this->marksChanged($locked, $data)) {
                $errors = MarkParts::errors($applied->only(ClassSubject::MARK_FIELDS));

                if ($errors !== []) {
                    throw ValidationException::withMessages(array_map(fn (string $message) => [$message], $errors));
                }

                abort_if(
                    $this->exams->hasMarksForSubject($locked),
                    409,
                    'Marks have already been entered for this subject, so its full and pass marks cannot be changed.'
                );
            }

            return $this->exams->updateSubject($locked, $data);
        });
    }

    /**
     * Whether the input changes any part mark from the saved value, so resending the same
     * marks together with a new date is fine once marks exist.
     *
     * @param  array<string, mixed>  $data
     */
    private function marksChanged(ExamSubject $saved, array $data): bool
    {
        foreach (ClassSubject::MARK_FIELDS as $field) {
            if (array_key_exists($field, $data) && ($data[$field] === null ? null : (int) $data[$field]) !== $saved->{$field}) {
                return true;
            }
        }

        return false;
    }

    /**
     * The exam date falls on or between the exam's start and end dates, checked against the
     * subject with the input applied (the pattern of the other rules here).
     */
    private function ensureDateWithinExam(ExamSubject $subject, Exam $exam): void
    {
        $date = $subject->exam_date?->toDateString();
        $start = $exam->start_date->toDateString();
        $end = $exam->end_date->toDateString();

        if ($date !== null && ($date < $start || $date > $end)) {
            throw ValidationException::withMessages([
                'exam_date' => ["The exam date must be within the exam's dates ({$start} to {$end})."],
            ]);
        }
    }

    private function ensureTimesInOrder(ExamSubject $subject): void
    {
        $start = $subject->start_time !== null ? substr((string) $subject->start_time, 0, 5) : null;
        $end = $subject->end_time !== null ? substr((string) $subject->end_time, 0, 5) : null;

        if ($start !== null && $end !== null && $end <= $start) {
            throw ValidationException::withMessages([
                'end_time' => ['The end time must be after the start time.'],
            ]);
        }
    }
}
